version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: laravel_app_dev
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=music_library
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_CONNECTION=pgsql
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_SCHEME=http
    depends_on:
      - postgres
      - elasticsearch
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx_dev
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
    depends_on:
      - app
    networks:
      - laravel_network

  postgres:
    image: postgres:15-alpine
    container_name: laravel_postgres_dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=music_library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: laravel_elasticsearch_dev
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - laravel_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: laravel_kibana_dev
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - laravel_network

volumes:
  postgres_data:
  elasticsearch_data:

networks:
  laravel_network:
    driver: bridge 