version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: laravel_app_dev
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=music_library
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_CONNECTION=pgsql
    depends_on:
      - postgres
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx_dev
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
    depends_on:
      - app
    networks:
      - laravel_network

  postgres:
    image: postgres:15-alpine
    container_name: laravel_postgres_dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=music_library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_network

volumes:
  postgres_data:

networks:
  laravel_network:
    driver: bridge 